name: main workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Create env file'
      run: |
       echo "${{ secrets.ENV_FILE }}" > .env

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: |
        pip install pipenv
        pipenv install --dev

    - name: Configure AWS profile
      run: |
        aws configure set region us-east-1 --profile default
        aws configure set output json --profile default
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default

    - name: Zappa deployment
      run: pipenv run zappa update prod